language: julia

os:
  - linux
  #- osx

julia:
  - 1.1
  #- 1.0
  #- nightly

matrix:
  allow_failures:
    - julia: nightly

addons:
  apt_packages:
    - gfortran

branches:
  only:
    - docs-testing
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # tags

before_install:
  - if [ `uname` == "Linux" ]; then unset DY_LIBRARY_PATH; fi
  - if [ `uname` == "Darwin" ]; then brew update; brew cask uninstall oclint; brew install gcc; brew tap optimizers/cutest; brew install cutest; brew install mastsif; for f in "archdefs" "sifdecode" "mastsif" "cutest"; do source $(brew --prefix $f)/$f.bashrc; done; fi
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

install:
  - julia -E 'using Pkg; Pkg.clone(pwd()); Pkg.build("CUTEst");'

script:
  - julia --check-bounds=yes -E 'using Pkg; Pkg.test("CUTEst"; coverage=true)'

jobs:
  include:
    - stage: Documentation
      julia: 1.1
      os: Linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs docs/make.jl
      after_success: skip

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("CUTEst")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())'
